/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz_Grafica;

import static BaseDeDatos.BDSentenciasADM.ApellidoAdmin;
import static BaseDeDatos.BDSentenciasADM.Codigo;
import static BaseDeDatos.BDSentenciasADM.NombreAdmin;
import static BaseDeDatos.BDSentenciasADM.TipoUsuarioAdmin;
import static BaseDeDatos.BDSentenciasEST.Apellido;
import static BaseDeDatos.BDSentenciasEST.Matricula;
import static BaseDeDatos.BDSentenciasEST.Nombre;
import static BaseDeDatos.BDSentenciasEST.TipoUsuario;
import static BaseDeDatos.BDSentenciasADM.AprobacionAdmin;
import javax.swing.JOptionPane;
import static BaseDeDatos.BDSentenciasEST.Aprobacion;

/**
 *
 * @author albe211
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /*
    static String Matricula;
    static String TipoUsuario;
    static String Nombre;
    static String Apellido;
    */
    
    public VentanaPrincipal() {
        initComponents();
        ColocarInofrmacion();
    }
    
    private void ColocarInofrmacion(){// en este metodo sirve para colocar la informacion del usuario ya logeado en los textos que tiene la Ventana Principal
 
      
        
        if (TipoUsuario.equals("Estudiante")){
            
            jMenuLibrosBiblioteca.setEnabled(false);
            jMenuPrestamosBiblioteca.setEnabled(false);
            jMenuGestionarUsuarios.setEnabled(false);
            jMenuItemCarreras.setEnabled(false);
            
            txtMatriculaVP.setText(Matricula);
            txtUsuarioVP.setText(Nombre + " " + Apellido);
            txtTipoUsuarioVP.setText(TipoUsuario);

            txtMatriculaVP.setEditable(false);
            txtUsuarioVP.setEditable(false);
            txtTipoUsuarioVP.setEditable(false);
        }
        
        if (TipoUsuarioAdmin.equals("Administrador")){
            jMenuRegistroPrestamo.setEnabled(false);
            jMenuCambiarContraseña.setEnabled(false);
            
            txtMatriculaVP.setText(Codigo);
            txtUsuarioVP.setText(NombreAdmin + " " + ApellidoAdmin);
            txtTipoUsuarioVP.setText(TipoUsuarioAdmin);

            txtMatriculaVP.setEditable(false);
            txtUsuarioVP.setEditable(false);
            txtTipoUsuarioVP.setEditable(false);

        }
    }
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioVP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipoUsuarioVP = new javax.swing.JTextField();
        txtMatriculaVP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSistema = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuPrestamo = new javax.swing.JMenu();
        jMenuRegistroPrestamo = new javax.swing.JMenuItem();
        jMenuBiblioteca = new javax.swing.JMenu();
        jMenuLibrosBiblioteca = new javax.swing.JMenuItem();
        jMenuPrestamosBiblioteca = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuGestionarUsuarios = new javax.swing.JMenuItem();
        jMenuItemCarreras = new javax.swing.JMenuItem();
        jMenuCambiarContraseña = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblio.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Matrícula:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatriculaVP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuarioVP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTipoUsuarioVP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtMatriculaVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtUsuarioVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtTipoUsuarioVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_pc_opt.png"))); // NOI18N
        jMenuSistema.setText("Sistema");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItem1);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuSalir);

        jMenuBar1.add(jMenuSistema);

        jMenuPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Prestamo_opt.png"))); // NOI18N
        jMenuPrestamo.setText("Péstamos");

        jMenuRegistroPrestamo.setText("Registro de Prestamo");
        jMenuRegistroPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistroPrestamoActionPerformed(evt);
            }
        });
        jMenuPrestamo.add(jMenuRegistroPrestamo);

        jMenuBar1.add(jMenuPrestamo);

        jMenuBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ibros_opt.png"))); // NOI18N
        jMenuBiblioteca.setText("Biblioteca");

        jMenuLibrosBiblioteca.setText("Libros");
        jMenuLibrosBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLibrosBibliotecaActionPerformed(evt);
            }
        });
        jMenuBiblioteca.add(jMenuLibrosBiblioteca);

        jMenuPrestamosBiblioteca.setText("Historial P/R");
        jMenuPrestamosBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrestamosBibliotecaActionPerformed(evt);
            }
        });
        jMenuBiblioteca.add(jMenuPrestamosBiblioteca);

        jMenuBar1.add(jMenuBiblioteca);

        jMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usarios_opt.png"))); // NOI18N
        jMenuUsuarios.setText("Usuarios");

        jMenuGestionarUsuarios.setText("Gestionar Usuarios");
        jMenuGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionarUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuGestionarUsuarios);

        jMenuItemCarreras.setText("Gestionar Carreras");
        jMenuItemCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarrerasActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCarreras);

        jMenuCambiarContraseña.setText("Cambiar Contraseña");
        jMenuCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCambiarContraseñaActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuCambiarContraseña);

        jMenuBar1.add(jMenuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLibrosBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLibrosBibliotecaActionPerformed
        // TODO add your handling code here:
        
        GestionLibros a = new GestionLibros();
        a.setVisible(true);
        a.pack();
    }//GEN-LAST:event_jMenuLibrosBibliotecaActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        
         System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionarUsuariosActionPerformed
        // TODO add your handling code here:
        
        GestionUsuarios a = new GestionUsuarios();
        a.setVisible(true);
        a.pack();
    }//GEN-LAST:event_jMenuGestionarUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        Aprobacion = 0;
        Matricula = ""; // variable que guardara la matricula del login para ponerlo en los otros frame
        TipoUsuario = "";
        Nombre = "";
        Apellido = "";
        AprobacionAdmin = 0;
        Codigo = ""; // variable que guardara la matricula del login para ponerlo en los otros frame
        TipoUsuarioAdmin = "";
        NombreAdmin = "";
        ApellidoAdmin = "";
           Login a = new Login();
           a.setVisible(true);
           a.pack();
           this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuPrestamosBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrestamosBibliotecaActionPerformed
        // TODO add your handling code here:
        ReservasBiblioteca a = new ReservasBiblioteca();
        a.setVisible(true);
        a.pack();
        
    }//GEN-LAST:event_jMenuPrestamosBibliotecaActionPerformed

    private void jMenuRegistroPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroPrestamoActionPerformed
        // TODO add your handling code here:
        
        PrestamoEstudiante a = new PrestamoEstudiante();
        a.setVisible(true);
        a.pack();
    }//GEN-LAST:event_jMenuRegistroPrestamoActionPerformed

    private void jMenuCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCambiarContraseñaActionPerformed
        // TODO add your handling code here:
        
        CambiarContraseña a = new CambiarContraseña();
        a.setVisible(true);
        a.pack();
    }//GEN-LAST:event_jMenuCambiarContraseñaActionPerformed

    private void jMenuItemCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarrerasActionPerformed
        // TODO add your handling code here:
        
         GestionCarrera a = new GestionCarrera();
        a.setVisible(true);
        a.pack();
    }//GEN-LAST:event_jMenuItemCarrerasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBiblioteca;
    private javax.swing.JMenuItem jMenuCambiarContraseña;
    private javax.swing.JMenuItem jMenuGestionarUsuarios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCarreras;
    private javax.swing.JMenuItem jMenuLibrosBiblioteca;
    private javax.swing.JMenu jMenuPrestamo;
    private javax.swing.JMenuItem jMenuPrestamosBiblioteca;
    private javax.swing.JMenuItem jMenuRegistroPrestamo;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jPanel1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    public javax.swing.JTextField txtMatriculaVP;
    public javax.swing.JTextField txtTipoUsuarioVP;
    public javax.swing.JTextField txtUsuarioVP;
    // End of variables declaration//GEN-END:variables
}
